_extends: .github

repository:
  name: NucleosLastFmBundle
  description: 🔌 This bundle provides services for using the last.fm API with symfony.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, symfony-bundle, bundle, php, lastfm, api, webservice-client
